name: Terraform workflow

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1
          aws configure set output json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Request Approval
        run: echo "Please approve the plan before applying."

      - name: Terraform Apply
        if: ${{ github.event.inputs.approve == 'true' }}
        run: terraform apply -auto-approve

  approval:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Wait for approval
        run: echo "Waiting for manual approval..."
        timeout-minutes: 60

      - name: Approve
        run: echo "Approved"
        env:
          approve: true
